namespace:
  name: zabbix-monitoring

rbac:
  create: true
  name: zabbix-kubernetes-discovery
  rolebinding: zabbix-kubernetes-discovery

serviceAccount:
  create: true
  name: zabbix-kubernetes-discovery

deployment:
  name: zabbix-kubernetes
  image:
    name: ghcr.io/axians-acsp/zabbix-kubernetes-discovery:v1.4.2
    pullPolicy: IfNotPresent
  replicas: 1
  strategy: Recreate

list_of_deployments:
  node:
    crontab_name: node
  daemonset:
    crontab_name: daemonset
  volume:
    crontab_name: volume
  deployment:
    crontab_name: deployment
  statefulset:
    crontab_name: statefulset
  cronjob:
    crontab_name: cronjob

environment:
  ZABBIX_ENDPOINT:
  KUBERNETES_NAME:
  #KUBECONFIG: "<kubeconfig_base64>"

zabbix:
  timeout: 5
  verbose: 'no'
  debug: 'no'

monitoring:
  global_exclude_namespace: "fr-*, testing"
  node:
    exclude_name: ''
  daemonset:
    exclude_name: ''
    exclude_namespace: ''
  volume:
    exclude_name: 'dump-redis-*'
    exclude_namespace: ''
  deployment:
    exclude_name: ''
    exclude_namespace: ''
  statefulset:
    exclude_name: ''
    exclude_namespace: ''
  cronjob:
    exclude_name: ''
    exclude_namespace: ''

crontab:
  name: zabbix-kubernetes
  node:
    discovery: '*/10 * * * *'
    item: '*/5 * * * *'
  daemonset:
    discovery: '*/10 * * * *'
    item: '*/5 * * * *'
  volume:
    discovery: '*/10 * * * *'
    item: '*/5 * * * *'
  deployment:
    discovery: '*/10 * * * *'
    item: '*/5 * * * *'
  statefulset:
    discovery: '*/10 * * * *'
    item: '*/5 * * * *'
  cronjob:
    discovery: '*/10 * * * *'
    item: '*/5 * * * *'

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 1Gi

nodeSelector:
  environment: General
  lifecycle: OnDemand
  project: DevOps
tolerations: []
affinity: {}
